name: aliallover
favicon: null
layout_spectrum: 0.99943
typography_spectrum: 0.57098
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#ede2cf'
    - '#c3b69a'
    - '#795934'
    - '#ad8a55'
  brandStrength: 0.8601212142966688
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
